---

driver:
  name: digitalocean
  size: s-1vcpu-1gb
  #size: 512mb
  private_networking: false
  region: lon1
  tags: do_test_pool
  firewalls: bca4bb7a-bd17-467c-8a53-358b8368f371

# transport:
#   ssh_key: /home/tomhodder/.ssh/id_rsa_digitalocean

transport:
  ssh_key: ~/.ssh/id_rsa.do-buildbot

# verifier:
#   format: junit
#   output: reports/inspec/junit/<%= Time.now.strftime("%Y_%m_%d") %>/%{platform}_%{suite}_<%= Time.now.strftime("%H_%M_%S") %>_inspec.xml
#   name: inspec
#   # sudo: true
#   format: junit
#   output: reports/inspec/junit/%{platform}_%{suite}_<%= Time.now %>_inspec.xml

platforms:
#   - name: debian-8
  - name: debian-9
  - name: ubuntu-18
  - name: ubuntu-16
  #- name: ubuntu-14
  - name: centos-7
  - name: centos-6
  - name: fedora-28
  # - name: oracle-7.4
  # - name: oracle-6.9
