---

- tags: [ mysql ]
  become: yes
  block:

  - debug:
      var: rprofile

  - name: call the distro specific tasks for Mysql
    include_tasks: "{{ include_mysql_tasks }}"
    with_first_found:
    - files:
        - "{{ rprofile }}-{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
        - "{{ rprofile }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ rprofile }}-{{ ansible_distribution }}.yml"
        - "{{ rprofile }}-{{ ansible_os_family }}.yml"
        - "{{ rprofile }}-{{ ansible_system }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
    loop_control:
      loop_var: include_mysql_tasks
    tags: always
    # when: mysql_install

  - name: if nothing else started the server, start it now
    service:
      name: "{{ mysql_service_name }}"
      state: started
      enabled: yes

  - include_tasks: validation.yml
