---

- tags: [ mysql ]
  become: yes
  block:

    # boilerplate
  - name: bootstrap enough that ansible can run most ansible modules
    include_tasks: "bootstrap/main.yml"
    when: bootstrap_done is not defined
    tags: [ bootstrap ]

    # boilerplate
  - set_fact:
      rprofile: "{{ mysql_profile }}"
    when: mysql_profile is defined

  - include_tasks: bootstrap/distro-vars-import-profile.yml
    tags: always

    ## START OF MAIN TASKS SECTION ##

  - name: generate a complex password for root
    set_fact:
      mysql_root_password: "{{ lookup('complex_password',
      '{{ store_path }}/{{ ansible_hostname }}/mysql/root_pass length=15 chars=ascii_lowercase,ascii_uppercase,digits,#][()<>?@£~:;') }}"
    when: mysql_root_password is not defined
    tags: always

  - name: generate a complex password for ansible_dba
    set_fact:
      mysql_dba_password: "{{ lookup('complex_password',
      '{{ store_path }}/{{ ansible_hostname }}/mysql/mysql_dba_password length=15 chars=ascii_lowercase,ascii_uppercase,digits,#][()<>?@£~:;') }}"
    when: mysql_dba_password is not defined
    tags: always

  - name: need to persist the mysql_dba_user value for tests
    set_fact:
      mysql_dba_user: "{{ mysql_dba_user }}"
    tags: always

  - name: need to persist the mysql_dba_user value for tests
    set_fact:
      mysql_dba_user: "{{ mysql_dba_user }}"
    tags: always

    # setup the root user
  - include_tasks: opt/configure/root.yml
    tags: always

  - debug:
      var: mysql_install

  - include_tasks: install/main.yml
    when: mysql_install
    tags: always

  # - set_fact:
  #     limepepper_mysql:
  #       logfiles:
  #         limepepper.mysql:
  #           files: "{{ mysql_profiles[mysql_profile]['log_files'] }}"
  #   tags: always

  - debug:
      var: limepepper_mysql

    ## END OF MAIN TASKS SECTION ##

  # boilerplate
  # the idea here, is that if any of the tasks fail, it will add useful
  # troubleshooing tools to the build.
  rescue:
  - include_tasks: bootstrap/distro-debug-packages.yml

  - fail:
      msg: "force a failure due to previous errors"
