#!/bin/bash

: <<EOREM

This script populates HOSTVAR_XX variables for use in other utilites

EOREM


#    ____  _       _    __                      ____       _            _
#   |  _ \| | __ _| |_ / _| ___  _ __ _ __ ___ |  _ \  ___| |_ ___  ___| |_
#   | |_) | |/ _` | __| |_ / _ \| '__| '_ ` _ \| | | |/ _ \ __/ _ \/ __| __|
#   |  __/| | (_| | |_|  _| (_) | |  | | | | | | |_| |  __/ ||  __/ (__| |_
#   |_|   |_|\__,_|\__|_|  \___/|_|  |_| |_| |_|____/ \___|\__\___|\___|\__|
#

export HOSTVAR_ARCH=$(uname -m)

case $OSTYPE in

darwin*)
platform="mac"
;;
linux-gnu)


if [[ -f /etc/fedora-release ]] ; then

[[ "$(cat /etc/fedora-release)" =~ ^Fedora ]] && \
{
export HOSTVAR_OS_FAMILY=RedHat
export HOSTVAR_OS_DISTRIBUTION=Fedora
export HOSTVAR_OS_MAJOR_VERSION=$(cat /etc/fedora-release | cut -d' ' -f3 | cut -d'.' -f1)
export HOSTVAR_OS_VERSION="$(cat /etc/fedora-release | cut -d' ' -f3)"
case $HOSTVAR_OS_MAJOR_VERSION in
  [26-27])
    export HOSTVAR_PKG_MANAGER=dnf
    export HOSTVAR_SERVICE_MANAGER=systemd
  ;;
esac
}

elif  [[ -f /etc/centos-release ]] ; then

[[ "$(cat /etc/centos-release)" =~ ^CentOS ]] && \
{
export HOSTVAR_OS_FAMILY=RedHat
export HOSTVAR_OS_DISTRIBUTION=CentOS
export HOSTVAR_OS_MAJOR_VERSION=$(rpm -q --queryformat '%{VERSION}' centos-release)
export HOSTVAR_OS_VERSION="$(cat /etc/centos-release | cut -d' ' -f4)"

case $HOSTVAR_OS_MAJOR_VERSION in
  [5-6])
    export HOSTVAR_PKG_MANAGER=yum
    export HOSTVAR_SERVICE_MANAGER=initd
  ;;
  7)
    export HOSTVAR_PKG_MANAGER=yum
    export HOSTVAR_SERVICE_MANAGER=systemd
  ;;  
esac

}

elif [[ -f /etc/redhat-release ]] ; then

[[ "$(cat /etc/redhat-release)" =~ ^RHEL ]] && \
{
  export HOSTVAR_OS_FAMILY=RedHat
  export HOSTVAR_OS_DISTRIBUTION=RHEL
  export HOSTVAR_OS_MAJOR_VERSION=$(rpm -q --queryformat '%{VERSION}' redhat-release)
  case $HOSTVAR_OS_MAJOR_VERSION in
    [5-6])
      export HOSTVAR_PKG_MANAGER=yum
      export HOSTVAR_SERVICE_MANAGER=initd
    ;;
    7)
      export HOSTVAR_PKG_MANAGER=yum
      export HOSTVAR_SERVICE_MANAGER=systemd
    ;;  
  esac
}

elif [ -f /etc/debian_version ] ; then
  export HOSTVAR_OS_FAMILY=Debian

  DIST=`cat /etc/lsb-release | grep '^DISTRIB_ID' | awk -F= '{ print $2 }'`
  PSUEDONAME=`cat /etc/lsb-release | grep '^DISTRIB_CODENAME' | awk -F= '{ print $2 }'`
  REV=`cat /etc/lsb-release | grep '^DISTRIB_RELEASE' | awk -F= '{ print $2 }'`


elif [ -f /etc/SuSE-release ] ; then
  DistroBasedOn='SuSe'
  PSUEDONAME=`cat /etc/SuSE-release | tr "\n" ' '| sed s/VERSION.*//`
  REV=`cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //`
elif [ -f /etc/mandrake-release ] ; then
  DistroBasedOn='Mandrake'
  PSUEDONAME=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
  REV=`cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//`

fi
;;
*)

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
fi

;;
esac


#    ____            _                    _   _       _  __
#   |  _ \ __ _  ___| | ____ _  __ _  ___| | | |_ __ (_)/ _|_   _
#   | |_) / _` |/ __| |/ / _` |/ _` |/ _ \ | | | '_ \| | |_| | | |
#   |  __/ (_| | (__|   < (_| | (_| |  __/ |_| | | | | |  _| |_| |
#   |_|   \__,_|\___|_|\_\__,_|\__, |\___|\___/|_| |_|_|_|  \__, |
#                              |___/                        |___/

function pkg_provides_fsobject()
{
case $HOSTVAR_PKG_MANAGER in
  yum|dnf)
    rpm -q --whatprovides $1
  ;;
  apt)
    dpkg -S $1
  ;;  
esac
}
export -f pkg_provides_fsobject

# This takes a string potentially containing wildcards and returns list
function pkg_search_names()
{
  SEARCHTERM="$1"
  case $HOSTVAR_PKG_MANAGER in
    yum|dnf)
      rpm -qa | egrep $SEARCHTERM
    ;;
    apt)
      dpkg -S $1
    ;;  
  esac

}
export -f pkg_search_names

#   __     __            _             __  __
#   \ \   / /__ _ __ ___(_) ___  _ __ |  \/  |_   _ _ __   __ _  ___
#    \ \ / / _ \ '__/ __| |/ _ \| '_ \| |\/| | | | | '_ \ / _` |/ _ \
#     \ V /  __/ |  \__ \ | (_) | | | | |  | | |_| | | | | (_| |  __/
#      \_/ \___|_|  |___/_|\___/|_| |_|_|  |_|\__,_|_| |_|\__, |\___|
#                                                         |___/

# attempt to make a sensible SemVer from some ridiculous string
_ver()
{
  while read -r  line; do
      echo $line | tr -d -c '[:digit:].' | cut -f1,2,3 -d'.'
  done
}
export -f _ver


