#!/bin/bash

echo $0

if [ "`basename $0`" = "mysql_size" ]; then

mysql $@ <<EOSQL
SELECT table_schema "Data Base Name",
sum( data_length + index_length ) / 1024 /
1024 "Data Base Size in MB",
sum( data_free )/ 1024 / 1024 "Free Space in MB"
FROM information_schema.TABLES
GROUP BY table_schema ; 
EOSQL



fi
